name: Auto-update versions.json

on:
  push:
    paths:
      - 'version.txt'
      - 'addons/**/version.txt'

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Update versions.json
        run: python update_versions_json.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add versions.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update versions.json"
            git push
          fi
